# Site settings
title: 1 stop drop shipping
email: support@1stopdropshipping.com
phone: +86 18123937936
address: Room 902, C2 Building,JinHengLi Garden, LongHua District,Shenzhen, China 518000

description: > # this means to ignore newlines until "baseurl:"
 1stopdropshipping is the best drop shipping agent for Shopify seller. And we Also serve as product sourcing agent for 
 online/Offline small business. If you are seller at Amazon, Ebay, Wish or other e-commerce platform, 
 we could help you with product sourcing, branding, private label, product research, shipping, packaging in 1 stop.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://1stopdropshipping.com" # the base hostname & protocol for your site
twitter_username: 1stopdropshipping

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "CEO 1stopdropshipping"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
