# Site settings
title: 1 stop drop shipping
email: surelcc@1stopdropshipping.com
description: > # this means to ignore newlines until "baseurl:"
 1stopdropshipping is the best product sourcing agent for small business which
 using aliexpress, shopify, ebay, wish or other e-commerce platform to do online business.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://1stopdropshipping.com" # the base hostname & protocol for your site
twitter_username: 1stopdropshipping

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "CEO 1stopdropshipping"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
